In [45]:
import numpy as np

# 初始化数据

In [46]:
training_set=np.array([[[3,3],1],[[4,3],1],[[1,1],-1]])
a=np.zeros(len(training_set),np.float)
b=0.0
Gram=None
y=np.array(training_set[:,1])
x=np.empty((len(training_set),2),np.float)
for i in range(len(training_set)):
    x[i]=training_set[i][0]

# 计算Gram矩阵

In [47]:
def cal_gram():
    g = np.empty((len(training_set),len(training_set)),np.int)
    for i in range(len(training_set)):
        for j in range(len(training_set)):
            g[i][j]=np.dot(training_set[i][0],training_set[j][0])
    return g

# 检查分类错误点

In [48]:
def check():
    global a,b,x,y
    flag=False
    for i in range(len(training_set)):
        if cal(i)<=0:
            flag=True
            update(i)
    if not flag:
        w=np.dot(a*y,x)
        print("RESULT w:"+str(w)+" b:" +str(b))
        return False
    return True

# 计算代价函数

In [49]:
def cal(i):
    global a,b,x,y
    res=np.dot(a*y,Gram[i])
    res=(res+b)*y[i]
    return res

# 更新a,b

In [50]:
def update(i):
    global a,b
    a[i]+=1
    b=b+y[i]
    print(a,b)

# 主函数

In [51]:
if __name__=="__main__":
    Gram=cal_gram()
    for i in range(1000):
        if not check():
            break

[1. 0. 0.] 1.0
[1. 0. 1.] 0.0
[1. 0. 2.] -1.0
[1. 0. 3.] -2.0
[2. 0. 3.] -1.0
[2. 0. 4.] -2.0
[2. 0. 5.] -3.0
RESULT w:[1.0 1.0] b:-3.0
